from pathlib import Path
from html import escape

ROOT = Path(__file__).parent

ICON_SPRITE = '''<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false"><defs>
<symbol id="i-snow" viewBox="0 0 24 24"><path d="M12 2v20M4.2 6.5l15.6 11M4.2 17.5l15.6-11M8.5 4.1 12 6l3.5-1.9M8.5 19.9 12 18l3.5 1.9M3.8 10 7 12l-3.2 2M20.2 10 17 12l3.2 2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></symbol>
<symbol id="i-flame" viewBox="0 0 24 24"><path d="M13.4 2.5c.6 4-2.9 5-2 8 1.1-.7 2.1-1.9 2.3-3.2 2.9 2.3 4.7 5.1 4.1 8.5-.5 3.2-2.8 5.7-6 5.7-3.7 0-6.2-2.7-6.2-6.1 0-2.9 1.5-5.4 4.2-7.8-.2 2 .7 3.3 1.4 3.8-1-4.1.8-7 2.2-8.9Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></symbol>
<symbol id="i-tool" viewBox="0 0 24 24"><path d="M14 6.4a5 5 0 0 0-6.8 6.5L2.8 17.3a2.8 2.8 0 0 0 4 4l4.4-4.4a5 5 0 0 0 6.5-6.8l-3 3-3.6-.9-.9-3.6 3.8-2.2Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></symbol>
<symbol id="i-home" viewBox="0 0 24 24"><path d="m3 11 9-8 9 8M5.5 9.5V21h13V9.5M9 21v-7h6v7" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></symbol>
<symbol id="i-calendar" viewBox="0 0 24 24"><path d="M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2Zm2-2v4m10-4v4M3 9h18M7 13h3m4 0h3m-10 4h3m4 0h3" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></symbol>
<symbol id="i-air" viewBox="0 0 24 24"><path d="M3 7h11c4 0 4-5 1-5-1.5 0-2.2.8-2.5 1.5M3 12h16c4 0 4 6 0 6-1.5 0-2.4-.8-2.7-1.8M3 17h8c3 0 3 4 0 4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></symbol>
<symbol id="i-building" viewBox="0 0 24 24"><path d="M4 21V5l8-3v19m0-13 8 2v11M2 21h20M7 7h2m-2 4h2m-2 4h2m6-3h2m-2 4h2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></symbol>
<symbol id="i-phone" viewBox="0 0 24 24"><path d="M7.1 2.8 10 7.5 7.8 9.8c1.4 3 3.5 5.1 6.5 6.5l2.3-2.2 4.7 2.8-.5 3.5c-.2 1-1.1 1.7-2.1 1.6C9.8 21.2 2.8 14.2 2 5.3c-.1-1 .6-1.9 1.6-2.1l3.5-.4Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></symbol>
<symbol id="i-shield" viewBox="0 0 24 24"><path d="M12 2 4 5v6c0 5.1 3.2 9.3 8 11 4.8-1.7 8-5.9 8-11V5l-8-3Zm-3.2 10 2.1 2.1 4.6-4.7" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></symbol>
</defs></svg>'''

def icon(name):
    return f'<svg aria-hidden="true"><use href="#i-{name}"></use></svg>'

def header(active=""):
    nav = [("Home","index.html","home"),("Services","services.html","services"),("Maintenance","maintenance.html","maintenance"),("About","about.html","about"),("Service Areas","service-area.html","areas"),("Contact","contact.html","contact")]
    links = ''.join(f'<a href="{href}"' + (' aria-current="page"' if key == active else '') + f'>{label}</a>' for label,href,key in nav)
    return f'''<!-- CUSTOMIZE: SERVICE AREA / HOURS -->
<div class="utility-bar"><div class="container utility-inner"><span>Serving Dallas–Fort Worth &amp; surrounding areas</span><span>Demo hours: Mon–Sat • 7 AM–8 PM</span></div></div>
<header class="site-header">
  <div class="container nav-row">
    <!-- CUSTOMIZE: COMPANY NAME / LOGO -->
    <a class="brand" href="index.html" aria-label="Summit Comfort Heating and Air home"><span class="brand-mark">{icon('snow')}</span><span class="brand-copy">SUMMIT COMFORT<small>Heating &amp; Air</small></span></a>
    <nav class="desktop-nav" aria-label="Primary navigation">{links}</nav>
    <div class="header-actions"><a class="header-phone" href="tel:+12145550147" data-cta="header-call">Call now<strong>(214) 555-0147</strong></a><a class="button button-accent" href="contact.html#request-service" data-cta="header-request-service">Request Service</a></div>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu"><span></span></button>
  </div>
  <nav class="mobile-nav" id="mobile-menu" aria-label="Mobile navigation">{links}<a class="button button-accent" href="contact.html#request-service" data-cta="mobile-menu-request">Request Service</a></nav>
</header>'''

def footer():
    return f'''<section class="final-cta"><div class="container final-cta-inner"><div><p class="eyebrow">Comfort starts with a conversation</p><h2>Need Heating or Cooling Help?</h2><p>Whether you’re dealing with an AC problem, planning a replacement, or simply need seasonal maintenance, take the next step by phone or online.</p></div><div class="button-row"><a class="button button-light" href="tel:+12145550147" data-cta="footer-call">{icon('phone')} Call (214) 555-0147</a><a class="button button-accent" href="contact.html#request-service" data-cta="footer-request">Request Service</a></div></div></section>
<footer class="site-footer"><div class="container">
  <div class="footer-grid">
    <div class="footer-brand"><a class="brand" href="index.html" aria-label="Summit Comfort home"><span class="brand-mark">{icon('snow')}</span><span class="brand-copy">SUMMIT COMFORT<small>Heating &amp; Air</small></span></a><p>A fictional, prospect-ready HVAC website concept for Dallas–Fort Worth homeowners and small businesses.</p></div>
    <div><div class="footer-title">Services</div><div class="footer-links"><a href="ac-repair.html">AC Repair</a><a href="heating.html">Heating Repair</a><a href="hvac-installation.html">HVAC Installation</a><a href="maintenance.html">Maintenance</a><a href="indoor-air-quality.html">Indoor Air Quality</a><a href="services.html#commercial">Commercial HVAC</a></div></div>
    <div><div class="footer-title">Company</div><div class="footer-links"><a href="about.html">About</a><a href="service-area.html">Service Areas</a><a href="contact.html">Contact</a><a href="hvac-installation.html#financing">Financing</a></div></div>
    <div class="footer-contact"><div class="footer-title">Contact</div><!-- CUSTOMIZE: PHONE / EMAIL / HOURS --><a href="tel:+12145550147">(214) 555-0147</a><a href="mailto:service@summitcomfort.example">service@summitcomfort.example</a><p>Dallas–Fort Worth, Texas</p><p>Demo hours: Mon–Sat, 7 AM–8 PM</p></div>
  </div>
  <div class="footer-bottom"><span>© <span data-year>2026</span> Summit Comfort. Fictional demo business; no service is provided.</span><div class="legal-links"><a href="contact.html#demo-policies">Privacy placeholder</a><a href="contact.html#demo-policies">Terms placeholder</a><a href="contact.html#accessibility">Accessibility</a></div></div>
</div></footer>
<div class="mobile-cta"><a class="button button-outline" href="tel:+12145550147" data-cta="mobile-call">{icon('phone')} Call Now</a><a class="button button-accent" href="contact.html#request-service" data-cta="mobile-request">Request Service</a></div>'''

def meta(title, description, slug):
    url = f'https://www.client-domain.example/hvac/{slug}' if slug else 'https://www.client-domain.example/hvac/'
    return f'''<meta name="description" content="{escape(description, quote=True)}">
<meta name="theme-color" content="#0B2748">
<!-- CUSTOMIZE: CANONICAL URL / SOCIAL SHARING URL BEFORE PRODUCTION -->
<link rel="canonical" href="{url}">
<meta property="og:type" content="website"><meta property="og:title" content="{escape(title, quote=True)}"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:url" content="{url}"><meta property="og:image" content="https://www.client-domain.example/hvac/assets/images/hvac-technician-hero.jpg">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ccircle cx='32' cy='32' r='32' fill='%230e6fbf'/%3E%3Cpath d='M32 10v44M13 21l38 22M13 43l38-22' stroke='white' stroke-width='5' stroke-linecap='round'/%3E%3C/svg%3E">
<title>{escape(title)}</title>'''

def page(title, description, slug, body, active="", home=False):
    schema = '''
<!-- LocalBusiness template: CUSTOMIZE all URLs, address, coordinates, opening hours, images and social profiles before production. Do not add ratings without verified review data. -->
<script type="application/ld+json">{
  "@context":"https://schema.org","@type":"HVACBusiness","name":"Summit Comfort Heating & Air","url":"https://www.client-domain.example/hvac/","telephone":"+1-214-555-0147","email":"service@summitcomfort.example","image":"https://www.client-domain.example/hvac/assets/images/hvac-technician-hero.jpg","logo":"https://www.client-domain.example/hvac/assets/images/client-logo.png","address":{"@type":"PostalAddress","addressLocality":"Dallas","addressRegion":"TX","addressCountry":"US"},"areaServed":["Dallas","Fort Worth","Arlington","Plano","Irving","Garland","Frisco","McKinney"],"openingHoursSpecification":[{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"opens":"07:00","closes":"20:00"}],"sameAs":[]
}</script>''' if home else ''
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">{meta(title, description, slug)}<link rel="preload" href="assets/images/hvac-technician-hero.jpg" as="image" fetchpriority="high"><link rel="stylesheet" href="css/style.css">{schema}</head>
<body>{ICON_SPRITE}<a class="skip-link" href="#main-content">Skip to main content</a>{header(active)}<main id="main-content">{body}</main>{footer()}<script src="js/main.js" defer></script></body></html>'''

def page_hero(kicker, heading, copy, current, cta="Request Service", cta_link="contact.html#request-service"):
    return f'''<section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span><span aria-current="page">{current}</span></nav><p class="eyebrow">{kicker}</p><h1>{heading}</h1><p>{copy}</p><div class="button-row"><a class="button button-accent" href="{cta_link}" data-cta="page-hero-primary">{cta}</a><a class="button button-light" href="tel:+12145550147" data-cta="page-hero-call">{icon('phone')} Call (214) 555-0147</a></div></div></section>'''

def sidebar(title="Ready to get comfortable?"):
    return f'''<aside class="sidebar-card" aria-label="Service contact"><p class="eyebrow">Talk with our team</p><h2>{title}</h2><p>Tell us what your system is doing and we’ll help you request the appropriate next appointment.</p><a class="button button-accent" href="contact.html#request-service">Request Service</a><a class="phone-block" href="tel:+12145550147">(214) 555-0147</a><p class="demo-disclaimer">Demo contact information—replace before launch.</p></aside>'''

def service_page(kicker, heading, description, current, active, intro_heading, intro, symptoms, sections, cta):
    symptom_html=''.join(f'<li>{s}</li>' for s in symptoms)
    section_html=''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in sections)
    body=page_hero(kicker,heading,description,current,cta)+f'''<section class="section"><div class="container content-grid"><article class="content-copy"><h2>{intro_heading}</h2><p>{intro}</p><ul class="symptom-grid">{symptom_html}</ul>{section_html}<div class="button-row"><a class="button button-accent" href="contact.html#request-service">{cta}</a><a class="button button-outline" href="services.html">View All Services</a></div></article>{sidebar()}</div></section>'''
    return page(f'{current} in Dallas–Fort Worth | Summit Comfort Heating & Air',description,active+'.html',body,active if active in ['maintenance'] else 'services')

service_cards = [
('snow','AC Repair','AC blowing warm air, cycling frequently, or not turning on? Start with a focused cooling-system evaluation.','ac-repair.html','AC Repair Services'),
('flame','Heating Repair','No heat, uneven rooms, or a furnace making unfamiliar sounds? Request practical heating help.','heating.html','Heating Repair Services'),
('home','HVAC Installation','Compare replacement options around comfort, efficiency, system sizing, and budget.','hvac-installation.html','Explore Installation'),
('calendar','Preventive Maintenance','Plan seasonal checks that help identify performance concerns before peak weather.','maintenance.html','View Maintenance'),
('air','Indoor Air Quality','Explore filtration, humidity, ventilation, duct, and control options for your home.','indoor-air-quality.html','Air Quality Options'),
('building','Commercial HVAC','Heating and cooling support for light-commercial properties and small businesses.','services.html#commercial','Commercial Services')]

def cards():
    return ''.join(f'<a class="service-card" href="{href}"><span class="service-icon">{icon(ic)}</span><h3>{title}</h3><p>{copy}</p><span class="text-link">{label} <span aria-hidden="true">→</span></span></a>' for ic,title,copy,href,label in service_cards)

home_body=f'''<section class="hero"><figure class="hero-media"><img src="assets/images/hvac-technician-hero.jpg" width="1600" height="900" alt="HVAC technician checking gauges on a residential outdoor air-conditioning unit" fetchpriority="high"></figure><div class="container hero-inner"><div class="hero-copy"><p class="eyebrow">Heating • Cooling • Indoor Air Quality</p><h1>Reliable Heating &amp; AC Service Across Dallas–Fort Worth</h1><p class="lead">Professional heating and cooling service for homeowners throughout the DFW area. From urgent AC repairs to complete system replacements, Summit Comfort helps make the next step clear.</p><div class="button-row"><a class="button button-accent" href="contact.html#request-service" data-cta="hero-request-service">Request Service</a><a class="button button-light" href="tel:+12145550147" data-cta="hero-call">{icon('phone')} Call (214) 555-0147</a></div><p class="reassurance"><span>Flexible scheduling</span><span>Residential &amp; light commercial</span><span>Financing options available*</span></p><p class="hero-note">*Demo offering. Replace with verified client details.</p></div></div></section>
<section class="trust-strip" aria-label="Service values"><div class="container trust-grid"><div class="trust-item"><span class="trust-icon">{icon('home')}</span>Locally Operated</div><div class="trust-item"><span class="trust-icon">{icon('shield')}</span>Upfront Communication</div><div class="trust-item"><span class="trust-icon">{icon('calendar')}</span>Flexible Scheduling</div><div class="trust-item"><span class="trust-icon">{icon('building')}</span>Homes &amp; Small Businesses</div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading"><div><p class="eyebrow">Find the right service</p><h2>How Can We Help?</h2></div><p>Start with the problem you’re experiencing. Each service page explains common symptoms and a clear next step.</p></div><div class="services-grid">{cards()}</div></div></section>
<section class="section"><div class="container"><div class="urgent-panel"><div><p class="eyebrow">Cooling problem?</p><h2>AC Down on a Hot Texas Day?</h2><p>If your cooling system stops working, getting help shouldn’t be complicated. Call our service team and we’ll help you request the next available appointment.</p></div><div class="urgent-actions"><a class="button button-light" href="tel:+12145550147" data-cta="urgent-call">{icon('phone')} Call Now</a><a class="button button-accent" href="contact.html#request-service" data-cta="urgent-request">Request Service</a></div></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading"><div><p class="eyebrow">Professional service, made practical</p><h2>Why Homeowners Choose Summit Comfort</h2></div><p>No hype—just the details customers want from a home-service company.</p></div><div class="feature-grid"><div class="feature"><h3>Clear Communication</h3><p>We explain the issue and available options before work begins.</p></div><div class="feature"><h3>Respect for Your Home</h3><p>Service designed around keeping your property clean and protected.</p></div><div class="feature"><h3>Experienced Service</h3><p>Support for common residential heating and cooling systems.</p></div><div class="feature"><h3>Straightforward Scheduling</h3><p>Simple ways to request service online or by phone.</p></div><div class="feature"><h3>Local Focus</h3><p>Built around homeowners throughout the Dallas–Fort Worth area.</p></div><div class="feature"><h3>Long-Term Comfort</h3><p>Options considered around reliability, efficiency, and your home.</p></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Social proof template</p><h2>What Local Homeowners Say</h2></div><p>These clearly labeled samples show where a client’s verified reviews would appear.</p></div><div class="reviews-grid"><!-- DEMO TESTIMONIAL — REPLACE WITH REAL CUSTOMER REVIEW --><article class="review-card"><span class="review-label">Demo testimonial</span><p class="review-quote">“The scheduling process was simple, and the technician explained the options in a way that was easy to understand.”</p><p class="review-meta">Sample Customer <span>Dallas, TX • Replace review source</span></p></article><!-- DEMO TESTIMONIAL — REPLACE WITH REAL CUSTOMER REVIEW --><article class="review-card"><span class="review-label">Demo testimonial</span><p class="review-quote">“We knew what to expect before moving forward, and the work area was left clean when the appointment was finished.”</p><p class="review-meta">Sample Customer <span>Plano, TX • Replace review source</span></p></article><!-- DEMO TESTIMONIAL — REPLACE WITH REAL CUSTOMER REVIEW --><article class="review-card"><span class="review-label">Demo testimonial</span><p class="review-quote">“The team helped us compare repair and replacement paths without making the conversation feel pressured.”</p><p class="review-meta">Sample Customer <span>Arlington, TX • Replace review source</span></p></article></div></div></section>
<section class="section section-soft"><div class="container split"><div><p class="eyebrow">Replacement &amp; installation</p><h2>Thinking About Replacing Your HVAC System?</h2><p>A new heating and cooling system is a major home investment. Compare appropriate options based on comfort, efficiency, home size, and budget.</p><ul class="check-list"><li>Energy-efficient equipment options</li><li>Heat pump and traditional split systems</li><li>Smart thermostat compatibility</li><li>System sizing consultation</li><li>Financing options for qualified customers*</li></ul><div class="button-row"><a class="button button-accent" href="contact.html?service=installation#request-service" data-cta="replacement-estimate">Request an Estimate</a><a class="button button-outline" href="hvac-installation.html">Explore Installation</a></div><p class="demo-disclaimer">*CUSTOMIZE: Confirm financing availability and terms.</p></div><div class="equipment-art" role="img" aria-label="Stylized residential outdoor HVAC condenser"><div class="equipment-visual"></div></div></div></section>
<section class="section"><div class="container membership"><div class="membership-grid"><div class="membership-brand"><span>Summit Comfort Plan</span><strong>Protect your comfort year-round.</strong></div><div class="membership-content"><p class="eyebrow">Maintenance membership</p><h2>Make Seasonal Care Easier</h2><p>Turn routine system care into a simple, repeatable plan.</p><ul class="check-list"><li>Seasonal HVAC inspections</li><li>Maintenance reminders</li><li>System performance checks</li><li>Priority scheduling*</li><li>Repair discounts*</li><li>Reduced diagnostic fees*</li></ul><a class="button button-accent" href="maintenance.html#plan" data-cta="maintenance-plan">View Maintenance Plan</a><p class="demo-disclaimer">*Membership benefits are demo placeholders and require client confirmation.</p></div></div></div></section>
<section class="finance-band"><div class="container finance-inner"><div><p class="eyebrow">Financing placeholder</p><h2>Comfort Shouldn’t Have to Wait</h2><p>Ask about available financing options for qualified customers. No rates or approval claims are represented in this demo.</p></div><a class="button button-outline" href="hvac-installation.html#financing" data-cta="financing">Explore Financing</a></div></section>
<section class="section"><div class="container split"><div class="media-panel"><img src="assets/images/hvac-technician-hero.jpg" width="1600" height="900" loading="lazy" alt="Local HVAC technician inspecting residential cooling equipment"><div class="media-badge">Real client team and fleet photography should replace this demo image.</div></div><div><p class="eyebrow">A more human service experience</p><h2>Local HVAC Service Built Around Your Home</h2><p>At Summit Comfort, the goal is simple: make heating and cooling service easier to understand. Homeowners deserve clear communication, professional workmanship, and practical options without unnecessary pressure.</p><a class="button button-outline" href="about.html">Meet Our Team</a></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading"><div><p class="eyebrow">What to expect</p><h2>A Clear Path Back to Comfort</h2></div></div><div class="process-grid"><div class="process-step"><h3>Request Service</h3><p>Call or submit the short service form with a few details.</p></div><div class="process-step"><h3>We Assess the Problem</h3><p>A technician evaluates the system and explains available options.</p></div><div class="process-step"><h3>Get Comfortable Again</h3><p>Choose the repair or solution that works for your home.</p></div></div></div></section>
<section class="section"><div class="container split"><div><p class="eyebrow">Local service area</p><h2>Proudly Serving Dallas–Fort Worth</h2><p>These demo cities show how a real contractor’s service footprint can be made easy to scan.</p><div class="area-grid">{''.join(f'<div class="area-chip">{c}</div>' for c in ['Dallas','Fort Worth','Arlington','Plano','Irving','Garland','Frisco','McKinney'])}</div><p>Don’t see your city? <a class="text-link" href="tel:+12145550147">Call to confirm availability →</a></p><a class="button button-outline" href="service-area.html">View All Service Areas</a></div><div><p class="eyebrow">Questions, answered</p><h2>HVAC Service FAQ</h2><div class="faq-list"><div class="faq-item"><button class="faq-question" aria-expanded="true" aria-controls="faq-1"><span>How quickly can I schedule HVAC service?</span><span aria-hidden="true">+</span></button><div class="faq-answer" id="faq-1"><p>Appointment availability changes throughout the season. Call or submit a request and the team can share the next available options.</p></div></div><div class="faq-item"><button class="faq-question" aria-expanded="false" aria-controls="faq-2"><span>Should I repair or replace my air conditioner?</span><span aria-hidden="true">+</span></button><div class="faq-answer" id="faq-2"><p>The right choice depends on the diagnosis, repair history, comfort, efficiency, and budget. A system evaluation can give you useful context.</p></div></div><div class="faq-item"><button class="faq-question" aria-expanded="false" aria-controls="faq-3"><span>Do you work on heat pumps?</span><span aria-hidden="true">+</span></button><div class="faq-answer" id="faq-3"><p>This demo includes heat-pump service. Replace this answer with the client’s verified equipment capabilities.</p></div></div><div class="faq-item"><button class="faq-question" aria-expanded="false" aria-controls="faq-4"><span>Do you offer commercial HVAC service?</span><span aria-hidden="true">+</span></button><div class="faq-answer" id="faq-4"><p>The concept includes light-commercial service for small businesses. Confirm the real client’s property and equipment scope.</p></div></div></div></div></div></section>'''

pages={}
pages['index.html']=page('Heating & AC Service in Dallas–Fort Worth | Summit Comfort','Professional heating, air-conditioning, installation, maintenance, and indoor air quality service across Dallas–Fort Worth. Request HVAC service today.','',home_body,'home',True)
pages['services.html']=page('HVAC Services in Dallas–Fort Worth | Summit Comfort','Explore air-conditioning, heating, installation, maintenance, indoor air quality, and light-commercial HVAC services in Dallas–Fort Worth.','services.html',page_hero('Heating, cooling & air quality','HVAC Services for DFW Homes &amp; Small Businesses','Choose the service that best matches the problem you are trying to solve. Each page is organized around real customer questions and a simple way to request help.','Services')+f'<section class="section section-soft"><div class="container"><div class="all-services">{cards()}</div><div id="commercial" class="urgent-panel" style="margin-top:40px"><div><p class="eyebrow">Light-commercial HVAC</p><h2>Comfort Support for Small Businesses</h2><p>Request repair, maintenance, or replacement guidance for qualifying light-commercial properties. Equipment and property scope must be confirmed with the real client.</p></div><div class="urgent-actions"><a class="button button-accent" href="contact.html?service=commercial#request-service">Request Commercial Service</a></div></div></div></section>','services')

pages['ac-repair.html']=service_page('Cooling service','AC Repair That Starts With a Clear Diagnosis','AC not cooling, blowing warm air, or making an unfamiliar sound? Request air-conditioning service across the Dallas–Fort Worth area.','AC Repair','ac-repair','What Is Your AC Doing?','Cooling problems can have many causes. A focused system evaluation helps identify what is happening before repair options are discussed.',['Blowing warm air','Weak airflow','System will not turn on','Frequent cycling','Unusual noises','Thermostat problems','Water around equipment','Higher energy usage'],[('Common Cooling Problems','Airflow restrictions, controls, electrical components, refrigerant circuits, drainage, and equipment condition can all affect cooling. A technician should evaluate the system rather than relying on one symptom alone.'),('Repair or Replacement?','A major repair is a good moment to compare cost, repair history, comfort, efficiency, and the condition of the overall system. Summit Comfort can organize those considerations without presenting one universal answer.')],'Schedule AC Repair')
pages['heating.html']=service_page('Heating service','Heating Repair for Furnaces &amp; Heat Pumps','No heat, uneven rooms, strange odors, or unusual equipment noise? Request practical heating service in the Dallas–Fort Worth area.','Heating Repair','heating','When Your Home Is Not Warming Up','Start with the symptoms you can safely observe. Do not open energized equipment or attempt repairs that should be handled by a qualified professional.',['No heat','Uneven temperatures','Furnace concerns','Heat pump concerns','Strange odors','Unusual noises','Short cycling','Thermostat issues'],[('Furnace and Heat Pump Support','Heating systems operate differently, so the right diagnostic path depends on the equipment in your home. Share the system type when you request service if you know it.'),('Safety Comes First','If you smell gas or suspect a carbon-monoxide concern, leave the property and contact the appropriate utility or emergency service. Do not use the website form for a safety emergency.')],'Schedule Heating Service')
pages['hvac-installation.html']=service_page('System replacement','HVAC Installation Planned Around Your Home','Compare heating and cooling replacement options based on comfort, equipment condition, efficiency goals, system sizing, and budget.','HVAC Installation','hvac-installation','When Replacement May Make Sense','There is no single age or repair threshold that fits every system. A useful replacement conversation considers the whole home and how the existing equipment is performing.',['Frequent repair needs','Persistent comfort problems','High operating costs','Uneven rooms','Humidity concerns','Changing home needs','Heat pump interest','Planned renovation'],[('Proper Sizing Matters','Equipment selection should consider the home, insulation, windows, duct system, occupancy, and climate—not just the capacity of the existing unit.'),('Compare the Right Options','A consultation can cover heat pumps, traditional split systems, efficiency levels, controls, warranties, and installation details relevant to the actual property.'),('Financing Options','Financing may be available for qualified customers through a client-approved provider. Replace this placeholder with verified provider disclosures, terms, and links before launch.')],'Request an Estimate')
pages['maintenance.html']=service_page('Seasonal system care','HVAC Maintenance Without the Guesswork','Plan seasonal inspections, performance checks, and reminders for your home’s heating and cooling equipment.','HVAC Maintenance','maintenance','A Practical Seasonal Routine','Maintenance is an opportunity to review condition, cleanliness, airflow, controls, and basic performance before peak cooling or heating demand.',['Equipment inspection','Filter considerations','Drainage checks','Electrical connections','Airflow review','Thermostat operation','Heating performance','Cooling performance'],[('What a Tune-Up Can Cover','The specific checklist should match the equipment, season, and client procedures. This demo intentionally avoids promising a universal checklist.'),('The Summit Comfort Plan','The membership section is structured for recurring-care benefits such as reminders, seasonal visits, priority scheduling, and discounts. Every benefit marked with an asterisk must be verified with the client.')],'Schedule a Tune-Up')
pages['indoor-air-quality.html']=service_page('Home comfort options','Indoor Air Quality Options for DFW Homes','Explore filtration, humidity, ventilation, duct, and control options without unsupported health claims.','Indoor Air Quality','indoor-air-quality','Start With the Home and the Concern','Indoor comfort can involve particles, humidity, stale air, odors, airflow, or controls. The right equipment depends on the source of the concern and the existing HVAC system.',['Air filtration','Humidity management','Ventilation options','Duct-related concerns','Airflow balance','Thermostat controls','Persistent odors','System compatibility'],[('Filtration and Airflow','Higher-efficiency filtration is not automatically appropriate for every system. Filter selection should consider equipment design and airflow requirements.'),('No Unsupported Health Promises','HVAC products may help manage certain indoor conditions, but this site does not claim to diagnose, treat, or prevent health conditions. Consult an appropriate professional for medical or environmental concerns.')],'Explore Air Quality Options')

about_body=page_hero('About Summit Comfort','Local Service Built Around Clear Communication','This fictional company story demonstrates how an HVAC contractor can present its people, philosophy, and local focus without inflated claims.','About Summit Comfort','Request Service')+f'''<section class="section"><div class="container split"><div class="media-panel"><img src="assets/images/hvac-technician-hero.jpg" width="1600" height="900" loading="lazy" alt="HVAC technician servicing an outdoor residential unit"><div class="media-badge">CUSTOMIZE: Replace with real owner or team photography.</div></div><div><p class="eyebrow">Our approach</p><h2>Make HVAC Service Easier to Understand</h2><p>At Summit Comfort, the goal is to give homeowners practical information, respectful service, and clear options. The strongest client version of this page should tell the real founder’s story in their own voice.</p><p>Use this space to explain why the company started, who it serves, what its team values, and how it participates in the local community.</p></div></div></section><section class="section section-soft"><div class="container"><div class="section-heading"><div><p class="eyebrow">Values</p><h2>What the Work Should Feel Like</h2></div></div><div class="feature-grid"><div class="feature"><h3>Clear</h3><p>Customers should understand the concern, the available options, and the next step.</p></div><div class="feature"><h3>Respectful</h3><p>Homes, schedules, and budgets deserve thoughtful treatment.</p></div><div class="feature"><h3>Practical</h3><p>Recommendations should connect to the property and the homeowner’s needs.</p></div><div class="feature"><h3>Local</h3><p>Service areas and availability should be represented accurately.</p></div><div class="feature"><h3>Professional</h3><p>Real team training, licenses, and credentials belong here once verified.</p></div><div class="feature"><h3>Accountable</h3><p>Follow-through and communication matter before, during, and after an appointment.</p></div></div></div></section><section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">CUSTOMIZE: Team</p><h2>Put Real People at the Center</h2><p>Replace these structured placeholders with approved portraits, roles, short bios, and relevant credentials.</p></div></div><div class="reviews-grid"><article class="review-card"><span class="review-label">Owner photo placeholder</span><h3>Owner / Founder</h3><p>Add a real photograph and a concise introduction in the owner’s voice.</p></article><article class="review-card"><span class="review-label">Team photo placeholder</span><h3>Service Team</h3><p>Show the technicians customers may meet and describe real training.</p></article><article class="review-card"><span class="review-label">Local photo placeholder</span><h3>Community Connection</h3><p>Feature approved shop, fleet, or community imagery from the service area.</p></article></div></div></section>'''
pages['about.html']=page('About Summit Comfort Heating & Air | Dallas–Fort Worth', 'Learn about Summit Comfort’s clear, respectful approach to residential heating and cooling service across Dallas–Fort Worth.','about.html',about_body,'about')

area_body=page_hero('Dallas–Fort Worth service area','Local HVAC Service Across the Metroplex','Explore the demo service footprint, then call to confirm that your address and equipment fall within current availability.','Service Areas','Confirm Your Area','tel:+12145550147')+f'''<section class="section section-soft"><div class="container split"><div><p class="eyebrow">CUSTOMIZE: Actual service area</p><h2>Cities Represented in This Demo</h2><p>These locations are sample data for the fictional Summit Comfort brand. A client version should include only verified cities, neighborhoods, ZIP codes, and travel limitations.</p><div class="area-grid">{''.join(f'<div class="area-chip">{c}</div>' for c in ['Dallas','Fort Worth','Arlington','Plano','Irving','Garland','Frisco','McKinney','Richardson','Carrollton','Grapevine','Grand Prairie'])}</div><p>Don’t see your city? Call <a class="text-link" href="tel:+12145550147">(214) 555-0147</a> to confirm availability.</p></div>{sidebar('Need to confirm your ZIP code?')}</div></section><section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Local landing-page foundation</p><h2>Accurate Service Areas Build Trust</h2></div></div><div class="feature-grid"><div class="feature"><h3>Clear Boundaries</h3><p>List only locations the company can serve reliably.</p></div><div class="feature"><h3>Useful Local Detail</h3><p>Add verified neighborhood, ZIP, and property information where it helps customers.</p></div><div class="feature"><h3>Easy Confirmation</h3><p>Give edge-of-area customers a quick phone path to check availability.</p></div></div></div></section>'''
pages['service-area.html']=page('HVAC Service Areas in Dallas–Fort Worth | Summit Comfort','View Summit Comfort’s example HVAC service areas across Dallas, Fort Worth, Arlington, Plano, Irving, Garland, Frisco, and McKinney.','service-area.html',area_body,'areas')

def form_html():
    return '''<form class="form-shell" data-demo-form novalidate><div class="form-grid"><div class="form-field"><label for="first-name">First name</label><input id="first-name" name="firstName" autocomplete="given-name" required></div><div class="form-field"><label for="last-name">Last name</label><input id="last-name" name="lastName" autocomplete="family-name" required></div><div class="form-field"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" required></div><div class="form-field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required></div><div class="form-field"><label for="zip">ZIP code</label><input id="zip" name="zip" inputmode="numeric" autocomplete="postal-code" pattern="[0-9]{5}(-[0-9]{4})?" required></div><div class="form-field"><label for="service">Service needed</label><select id="service" name="service" required><option value="">Choose a service</option><option>AC Repair</option><option>Heating Repair</option><option>HVAC Installation / Replacement</option><option>Maintenance</option><option>Indoor Air Quality</option><option>Commercial HVAC</option><option>Other</option></select></div><fieldset class="form-field full" style="border:0;padding:0;margin:0"><legend class="legend">Preferred contact method</legend><div class="radio-row"><label class="radio-option"><input type="radio" name="contactMethod" value="Phone" required><span>Phone</span></label><label class="radio-option"><input type="radio" name="contactMethod" value="Text"><span>Text</span></label><label class="radio-option"><input type="radio" name="contactMethod" value="Email"><span>Email</span></label></div></fieldset><div class="form-field full"><label for="message">Describe the problem</label><textarea id="message" name="message" placeholder="What is your system doing? When did the issue start?"></textarea></div><div class="form-field full"><label class="consent"><input type="checkbox" name="consent" required><span>I agree to be contacted regarding my service request.</span></label></div><div class="form-field full"><button class="button button-accent" type="submit" data-cta="contact-form-submit">Request Service</button><div class="form-status" role="status" tabindex="-1">Demo request received. Connect this form to the client’s CRM, email service, or scheduling platform before launch. No information was transmitted.</div></div></div></form>'''

contact_body=page_hero('Call or request online','Request HVAC Service','Tell us what your system is doing, how to reach you, and which service you need. This static demo does not transmit information.','Contact','Call (214) 555-0147','tel:+12145550147')+f'''<section class="section section-soft" id="request-service"><div class="container contact-layout"><div><p class="eyebrow">Contact details</p><h2>Start With the Easiest Option</h2><p>For immediate scheduling questions, call. For non-urgent requests, use the short form.</p><div class="contact-cards"><div class="contact-card"><strong>Phone</strong><a href="tel:+12145550147">(214) 555-0147</a></div><div class="contact-card"><strong>Email</strong><a href="mailto:service@summitcomfort.example">service@summitcomfort.example</a></div><div class="contact-card"><strong>Demo hours</strong><span>Monday–Saturday, 7 AM–8 PM</span></div><div class="contact-card"><strong>Service area</strong><span>Dallas–Fort Worth and sample surrounding cities</span></div><div class="contact-card"><strong>Customer-facing address</strong><span>Not listed in this demo. Add only a verified public location.</span></div></div></div><div><p class="eyebrow">Short service form</p><h2>How Can We Help?</h2>{form_html()}</div></div></section><section class="section" id="accessibility"><div class="container narrow"><p class="eyebrow">Accessibility</p><h2>Designed for More Customers</h2><p>This demo uses semantic structure, visible keyboard focus, labeled fields, keyboard-operable menus and accordions, large touch targets, readable contrast, and reduced-motion support. A production client site should also receive content, assistive-technology, and user testing.</p><div id="demo-policies"><h2>Policy Placeholders</h2><p>Privacy and terms content must be written for the client’s actual forms, analytics, call tracking, financing providers, messaging practices, and jurisdiction before launch.</p></div></div></section>'''
pages['contact.html']=page('Request HVAC Service in Dallas–Fort Worth | Summit Comfort','Call Summit Comfort or submit a short demo request form for heating, cooling, installation, maintenance, or indoor air quality service.','contact.html',contact_body,'contact')

for filename, content in pages.items():
    (ROOT / filename).write_text(content, encoding='utf-8', newline='\n')
print(f'Generated {len(pages)} HVAC pages.')
